import { decimal, index, int, mysqlEnum, mysqlTable, text, timestamp, foreignKey, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const products = mysqlTable("products", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 255 }).notNull(), description: text("description").notNull(), category: varchar("category", { length: 100 }).notNull(), imageUrl: text("imageUrl"), price: decimal("price", { precision: 12, scale: 2 }).notNull(), oldPrice: decimal("oldPrice", { precision: 12, scale: 2 }), stock: int("stock").notNull().default(0), isActive: int("isActive").notNull().default(1), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (table) => ({ categoryIdx: index("products_category_idx").on(table.category), activeIdx: index("products_active_idx").on(table.isActive) }));
export const addresses = mysqlTable("addresses", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), label: varchar("label", { length: 100 }).notNull(), line1: text("line1").notNull(), city: varchar("city", { length: 120 }).notNull(), country: varchar("country", { length: 120 }).notNull(), isDefault: int("isDefault").notNull().default(0), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ userIdx: index("addresses_user_idx").on(table.userId), userFk: foreignKey({ columns: [table.userId], foreignColumns: [users.id], name: "addresses_user_fk" }) }));
export const orders = mysqlTable("orders", { id: int("id").autoincrement().primaryKey(), orderNumber: varchar("orderNumber", { length: 32 }).notNull().unique(), idempotencyKey: varchar("idempotencyKey", { length: 128 }).notNull().unique(), userId: int("userId").notNull(), addressId: int("addressId"), status: mysqlEnum("status", ["pending", "processing", "shipped", "delivered", "cancelled"]).default("pending").notNull(), paymentStatus: mysqlEnum("paymentStatus", ["unpaid", "pending", "paid", "failed", "refunded"]).default("unpaid").notNull(), subtotal: decimal("subtotal", { precision: 12, scale: 2 }).notNull(), discount: decimal("discount", { precision: 12, scale: 2 }).notNull().default("0"), total: decimal("total", { precision: 12, scale: 2 }).notNull(), couponCode: varchar("couponCode", { length: 64 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (table) => ({ userIdx: index("orders_user_idx").on(table.userId), statusIdx: index("orders_status_idx").on(table.status), userFk: foreignKey({ columns: [table.userId], foreignColumns: [users.id], name: "orders_user_fk" }), addressFk: foreignKey({ columns: [table.addressId], foreignColumns: [addresses.id], name: "orders_address_fk" }) }));
export const orderItems = mysqlTable("order_items", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId").notNull(), productName: varchar("productName", { length: 255 }).notNull(), unitPrice: decimal("unitPrice", { precision: 12, scale: 2 }).notNull(), quantity: int("quantity").notNull(), lineTotal: decimal("lineTotal", { precision: 12, scale: 2 }).notNull() }, (table) => ({ orderFk: foreignKey({ columns: [table.orderId], foreignColumns: [orders.id], name: "order_items_order_fk" }), productFk: foreignKey({ columns: [table.productId], foreignColumns: [products.id], name: "order_items_product_fk" }) }));
export const coupons = mysqlTable("coupons", { id: int("id").autoincrement().primaryKey(), code: varchar("code", { length: 64 }).notNull().unique(), percentOff: int("percentOff").notNull(), minimumOrder: decimal("minimumOrder", { precision: 12, scale: 2 }).notNull().default("0"), usageLimit: int("usageLimit"), usedCount: int("usedCount").notNull().default(0), startsAt: timestamp("startsAt").notNull(), expiresAt: timestamp("expiresAt"), isActive: int("isActive").notNull().default(1) });
export const favorites = mysqlTable("favorites", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), productId: int("productId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ uniqueUserProduct: uniqueIndex("favorites_user_product_unique").on(table.userId, table.productId), userFk: foreignKey({ columns: [table.userId], foreignColumns: [users.id], name: "favorites_user_fk" }), productFk: foreignKey({ columns: [table.productId], foreignColumns: [products.id], name: "favorites_product_fk" }) }));
export const reviews = mysqlTable("reviews", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), productId: int("productId").notNull(), rating: int("rating").notNull(), body: text("body"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (table) => ({ productIdx: index("reviews_product_idx").on(table.productId), userIdx: index("reviews_user_idx").on(table.userId), userFk: foreignKey({ columns: [table.userId], foreignColumns: [users.id], name: "reviews_user_fk" }), productFk: foreignKey({ columns: [table.productId], foreignColumns: [products.id], name: "reviews_product_fk" }) }));

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Product = typeof products.$inferSelect; export type Order = typeof orders.$inferSelect; export type OrderItem = typeof orderItems.$inferSelect; export type Coupon = typeof coupons.$inferSelect;
