import { and, desc, eq, gte, like, inArray, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, products, orders, orderItems, coupons, addresses, favorites, reviews } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) _db = drizzle(process.env.DATABASE_URL); return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required"); const db = await getDb(); if (!db) throw new Error("Database is not configured"); const values: InsertUser = { openId: user.openId, lastSignedIn: user.lastSignedIn ?? new Date() }; const updateSet: Record<string, unknown> = { lastSignedIn: user.lastSignedIn ?? new Date() }; for (const field of ["name", "email", "loginMethod"] as const) if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0]; }
export async function listProducts(input: { includeInactive?: boolean; query?: string; category?: string; minPrice?: number; maxPrice?: number; sort?: "newest" | "price_asc" | "price_desc" }) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const filters = []; if (!input.includeInactive) filters.push(eq(products.isActive, 1)); if (input.category) filters.push(eq(products.category, input.category)); if (input.query?.trim()) filters.push(like(products.name, `%${input.query.trim()}%`)); if (input.minPrice !== undefined) filters.push(gte(products.price, input.minPrice.toFixed(2))); if (input.maxPrice !== undefined) filters.push(sql`${products.price} <= ${input.maxPrice.toFixed(2)}`); let query = db.select().from(products).where(filters.length ? and(...filters) : undefined); if (input.sort === "price_asc") query = query.orderBy(products.price) as typeof query; else if (input.sort === "price_desc") query = query.orderBy(desc(products.price)) as typeof query; else query = query.orderBy(desc(products.createdAt)) as typeof query; return query; }
export async function listUserOrders(userId: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const rows = await db.select().from(orders).where(eq(orders.userId, userId)).orderBy(desc(orders.createdAt)); const items = rows.length ? await db.select().from(orderItems).where(inArray(orderItems.orderId, rows.map((r) => r.id))) : []; return rows.map((order) => ({ ...order, items: items.filter((item) => item.orderId === order.id) })); }
export async function listAllOrders() { const db = await getDb(); if (!db) throw new Error("Database is not configured"); return db.select().from(orders).orderBy(desc(orders.createdAt)); }
export async function getAdminStats() { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const [productCount, orderCount, customerCount, sales] = await Promise.all([db.select({ count: sql<number>`count(*)` }).from(products).where(eq(products.isActive, 1)), db.select({ count: sql<number>`count(*)` }).from(orders), db.select({ count: sql<number>`count(*)` }).from(users).where(eq(users.role, "user")), db.select({ total: sql<string>`coalesce(sum(${orders.total}), 0)` }).from(orders).where(inArray(orders.status, ["processing", "shipped", "delivered"]))]); return { products: Number(productCount[0]?.count ?? 0), orders: Number(orderCount[0]?.count ?? 0), customers: Number(customerCount[0]?.count ?? 0), sales: Number(sales[0]?.total ?? 0) }; }
export async function createOrder(input: { userId: number; items: Array<{ productId: number; quantity: number }>; addressId?: number; couponCode?: string; idempotencyKey: string }) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const existing = (await db.select().from(orders).where(and(eq(orders.userId, input.userId), eq(orders.idempotencyKey, input.idempotencyKey))).limit(1))[0]; if (existing) return { orderId: existing.id, orderNumber: existing.orderNumber, subtotal: Number(existing.subtotal), discount: Number(existing.discount), total: Number(existing.total), paymentStatus: existing.paymentStatus }; const merged = new Map<number, number>(); for (const item of input.items) { if (!Number.isInteger(item.quantity) || item.quantity < 1) throw new Error("Invalid quantity"); merged.set(item.productId, (merged.get(item.productId) ?? 0) + item.quantity); } if (input.addressId) { const owned = await db.select().from(addresses).where(and(eq(addresses.id, input.addressId), eq(addresses.userId, input.userId))).limit(1); if (!owned.length) throw new Error("Address does not belong to this user"); } return db.transaction(async (tx) => { const ids = [...merged.keys()]; const productRows = await tx.select().from(products).where(inArray(products.id, ids)); if (productRows.length !== ids.length) throw new Error("One or more products are unavailable"); const lineItems = productRows.map((product) => { const quantity = merged.get(product.id)!; if (product.isActive !== 1) throw new Error("Product is inactive"); return { product, quantity, unitPrice: Number(product.price), lineTotal: Number(product.price) * quantity }; }); const subtotal = lineItems.reduce((sum, item) => sum + item.lineTotal, 0); let discount = 0; let couponCode: string | null = null; if (input.couponCode) { const code = input.couponCode.trim().toUpperCase(); const coupon = (await tx.select().from(coupons).where(and(eq(coupons.code, code), eq(coupons.isActive, 1))).limit(1))[0]; const now = new Date(); if (!coupon || coupon.startsAt > now || (coupon.expiresAt && coupon.expiresAt < now) || (coupon.usageLimit !== null && coupon.usedCount >= coupon.usageLimit) || subtotal < Number(coupon.minimumOrder)) throw new Error("Coupon is invalid or unavailable"); discount = Math.round(subtotal * coupon.percentOff / 100 * 100) / 100; couponCode = coupon.code; const couponUpdate = await tx.update(coupons).set({ usedCount: sql`${coupons.usedCount} + 1` }).where(and(eq(coupons.id, coupon.id), eq(coupons.isActive, 1), coupon.usageLimit === null ? sql`1=1` : sql`${coupons.usedCount} < ${coupon.usageLimit}`)); if (!couponUpdate[0] || (couponUpdate[0] as any).affectedRows !== undefined && (couponUpdate[0] as any).affectedRows !== 1) throw new Error("Coupon usage limit reached"); }
    for (const item of lineItems) { const result = await tx.update(products).set({ stock: sql`${products.stock} - ${item.quantity}` }).where(and(eq(products.id, item.product.id), eq(products.isActive, 1), gte(products.stock, item.quantity))); if ((result as any)[0]?.affectedRows !== undefined && (result as any)[0].affectedRows !== 1) throw new Error(`Insufficient stock for product ${item.product.id}`); }
    const total = Math.max(0, subtotal - discount); const orderNumber = `OM-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random() * 1000).toString().padStart(3, "0")}`; const inserted = await tx.insert(orders).values({ orderNumber, idempotencyKey: input.idempotencyKey, userId: input.userId, addressId: input.addressId ?? null, subtotal: subtotal.toFixed(2), discount: discount.toFixed(2), total: total.toFixed(2), couponCode }).$returningId(); const orderId = inserted[0]?.id; if (!orderId) throw new Error("Could not create order"); await tx.insert(orderItems).values(lineItems.map((item) => ({ orderId, productId: item.product.id, productName: item.product.name, unitPrice: item.unitPrice.toFixed(2), quantity: item.quantity, lineTotal: item.lineTotal.toFixed(2) }))); return { orderId, orderNumber, subtotal, discount, total, paymentStatus: "unpaid" as const }; }); }
const nextStatus: Record<string, string[]> = { pending: ["processing", "cancelled"], processing: ["shipped", "cancelled"], shipped: ["delivered"], delivered: [], cancelled: [] };
export async function updateOrderStatus(orderId: number, status: "pending" | "processing" | "shipped" | "delivered" | "cancelled") { const db = await getDb(); if (!db) throw new Error("Database is not configured"); return db.transaction(async (tx) => { const current = (await tx.select().from(orders).where(eq(orders.id, orderId)).limit(1))[0]; if (!current) throw new Error("Order not found"); if (current.status !== status && !nextStatus[current.status].includes(status)) throw new Error("Invalid order status transition"); if (status === "cancelled" && current.status !== "cancelled") { const items = await tx.select().from(orderItems).where(eq(orderItems.orderId, orderId)); for (const item of items) await tx.update(products).set({ stock: sql`${products.stock} + ${item.quantity}` }).where(eq(products.id, item.productId)); } await tx.update(orders).set({ status }).where(eq(orders.id, orderId)); return { ...current, status }; }); }
export async function listAddresses(userId: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); return db.select().from(addresses).where(eq(addresses.userId, userId)); }
export async function addAddress(userId: number, input: { label: string; line1: string; city: string; country: string; isDefault?: boolean }) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); if (input.isDefault) await db.update(addresses).set({ isDefault: 0 }).where(eq(addresses.userId, userId)); const row = await db.insert(addresses).values({ ...input, userId, isDefault: input.isDefault ? 1 : 0 }); return row; }
export async function listFavorites(userId: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); return db.select({ favorite: favorites, product: products }).from(favorites).innerJoin(products, eq(favorites.productId, products.id)).where(eq(favorites.userId, userId)); }
export async function toggleFavorite(userId: number, productId: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); const existing = await db.select().from(favorites).where(and(eq(favorites.userId, userId), eq(favorites.productId, productId))).limit(1); if (existing.length) { await db.delete(favorites).where(eq(favorites.id, existing[0].id)); return { liked: false }; } await db.insert(favorites).values({ userId, productId }); return { liked: true }; }
export async function listReviews(productId: number) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); return db.select().from(reviews).where(eq(reviews.productId, productId)).orderBy(desc(reviews.createdAt)); }
export async function addReview(userId: number, input: { productId: number; rating: number; body?: string }) { const db = await getDb(); if (!db) throw new Error("Database is not configured"); if (input.rating < 1 || input.rating > 5) throw new Error("Rating must be from 1 to 5"); const purchased = await db.select().from(orders).innerJoin(orderItems, eq(orders.id, orderItems.orderId)).where(and(eq(orders.userId, userId), eq(orderItems.productId, input.productId), eq(orders.status, "delivered"))).limit(1); if (!purchased.length) throw new Error("Only customers with a delivered order can review"); await db.insert(reviews).values({ userId, ...input }); return { success: true }; }
export { users, products, orders, orderItems, coupons, addresses, favorites, reviews };
